# Generated by Django 6.0.6 on 2026-06-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('dispatcher', 'Dispatcher'), ('driver', 'Driver'), ('passenger', 'Passenger')], default='dispatcher', max_length=20),
        ),
    ]
