# Generated by Django 6.0.6 on 2026-06-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Driver profile picture', null=True, upload_to='driver_photos/'),
        ),
    ]
