# Generated by Django 6.0.6 on 2026-06-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_driver_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='energy',
            field=models.PositiveSmallIntegerField(default=100, help_text='Fuel or battery percentage'),
        ),
    ]
